// 配色技法と調整技法の全定義
// データは TypeScript 側で一元管理し、Supabase の schemes テーブルへは
// supabase/migrations のシードSQLで同期する。

import type { Technique, AdjustmentTechnique } from './types';

export const techniques: Technique[] = [
  // ---------- hue_diff: 色相差ベース ----------
  {
    id: 'same_hue',
    nameJa: '同一色相配色',
    category: 'hue_diff',
    colorCount: { min: 2, max: 6 },
    hueRule: { kind: 'diff_range', min: 0, max: 0 },
    toneRule: { kind: 'any' },
    description: '同じ色相でまとめ、トーンの違いで変化をつける配色。',
    impression: ['統一感', 'まとまり', '落ち着き'],
    generationPriority: 'high',
  },
  {
    id: 'adjacent_hue',
    nameJa: '隣接色相配色',
    category: 'hue_diff',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'diff_range', min: 1, max: 1 },
    toneRule: { kind: 'any' },
    description: '隣り合う色相を使う、まとまりやすい配色。',
    impression: ['自然', '穏やか', 'まとまり'],
    generationPriority: 'high',
  },
  {
    id: 'similar_hue',
    nameJa: '類似色相配色',
    category: 'hue_diff',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'diff_range', min: 2, max: 3 },
    toneRule: { kind: 'any' },
    description: '近い色相を組み合わせる、調和しやすい配色。',
    impression: ['調和', '自然', 'やわらかい'],
    generationPriority: 'high',
  },
  {
    id: 'medium_difference_hue',
    nameJa: '中差色相配色',
    category: 'hue_diff',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'diff_range', min: 4, max: 7 },
    toneRule: { kind: 'any' },
    description: 'やや離れた色相を使い、適度な変化を出す配色。',
    impression: ['変化', '適度な対比', '動き'],
    generationPriority: 'medium',
  },
  {
    id: 'contrasting_hue',
    nameJa: '対照色相配色',
    category: 'hue_diff',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'diff_range', min: 8, max: 10 },
    toneRule: { kind: 'any' },
    description: '大きく離れた色相を使い、はっきりした印象を作る配色。',
    impression: ['明快', '対比', '活発'],
    generationPriority: 'medium',
  },
  {
    id: 'complementary_hue',
    nameJa: '補色色相配色',
    category: 'hue_diff',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'diff_range', min: 11, max: 12 },
    toneRule: { kind: 'any' },
    description: '補色関係にある色を使い、強い対比を作る配色。',
    impression: ['強い対比', '目立つ', '鮮やか'],
    generationPriority: 'high',
  },

  // ---------- tone_diff: トーン差ベース ----------
  {
    id: 'same_tone',
    nameJa: '同一トーン配色',
    category: 'tone_diff',
    colorCount: { min: 2, max: 6 },
    hueRule: { kind: 'any' },
    toneRule: { kind: 'same' },
    description: '同じトーンで色相を変える配色。印象が統一されやすい。',
    impression: ['統一感', '安定', 'まとまり'],
    generationPriority: 'high',
  },
  {
    id: 'similar_tone',
    nameJa: '類似トーン配色',
    category: 'tone_diff',
    colorCount: { min: 2, max: 6 },
    hueRule: { kind: 'any' },
    toneRule: { kind: 'similar' },
    description: '近いトーンでまとめる、穏やかで調和しやすい配色。',
    impression: ['穏やか', '調和', 'やさしい'],
    generationPriority: 'high',
  },
  {
    id: 'contrasting_tone',
    nameJa: '対照トーン配色',
    category: 'tone_diff',
    colorCount: { min: 2, max: 6 },
    hueRule: { kind: 'any' },
    toneRule: { kind: 'contrast' },
    description: '明度や彩度の差が大きいトーンを組み合わせる配色。',
    impression: ['強弱', 'メリハリ', '明快'],
    generationPriority: 'medium',
  },

  // ---------- dominant: 共通項配色 ----------
  {
    id: 'dominant_color',
    nameJa: 'ドミナントカラー配色',
    category: 'dominant',
    colorCount: { min: 3, max: 6 },
    hueRule: { kind: 'diff_range', min: 0, max: 3 },
    toneRule: { kind: 'any' },
    description: '色相に共通性を持たせ、トーンを変えてまとめる配色。',
    impression: ['統一感', 'まとまり', '色味の一貫性'],
    generationPriority: 'high',
  },
  {
    id: 'dominant_tone',
    nameJa: 'ドミナントトーン配色',
    category: 'dominant',
    colorCount: { min: 3, max: 6 },
    hueRule: { kind: 'any' },
    toneRule: { kind: 'similar' },
    description: 'トーンに共通性を持たせ、色相を変えてまとめる配色。',
    impression: ['統一感', '印象の一貫性', '調和'],
    generationPriority: 'high',
  },

  // ---------- tone_combo: トーン組み合わせ ----------
  {
    id: 'tone_on_tone',
    nameJa: 'トーンオントーン配色',
    category: 'tone_combo',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'diff_range', min: 0, max: 0 },
    toneRule: { kind: 'lightness_contrast' },
    description: '同じ色相で明度差を大きくつける配色。',
    impression: ['明快', 'はっきり', '濃淡'],
    generationPriority: 'high',
  },
  {
    id: 'tone_in_tone',
    nameJa: 'トーンイントーン配色',
    category: 'tone_combo',
    colorCount: { min: 2, max: 6 },
    hueRule: { kind: 'any' },
    toneRule: { kind: 'similar' },
    description: '同じ、または近いトーンでまとめる配色。',
    impression: ['まとまり', '穏やか', '統一感'],
    generationPriority: 'high',
  },
  {
    id: 'tonal',
    nameJa: 'トーナル配色',
    category: 'tone_combo',
    colorCount: { min: 2, max: 6 },
    hueRule: { kind: 'any' },
    toneRule: { kind: 'specific', tones: ['ltg', 'g', 'sf', 'd'] },
    description: '中明度・中彩度の落ち着いたトーンでまとめる配色。',
    impression: ['穏やか', '落ち着き', 'やわらかい'],
    generationPriority: 'medium',
  },

  // ---------- nuance: 微差配色 ----------
  {
    id: 'camaieu',
    nameJa: 'カマイユ配色',
    category: 'nuance',
    colorCount: { min: 2, max: 3 },
    hueRule: { kind: 'diff_range', min: 0, max: 1 },
    toneRule: { kind: 'similar' },
    description: '色相・トーンの差が非常に小さく、ほぼ単色に見える配色。',
    impression: ['繊細', '上品', '統一感'],
    generationPriority: 'medium',
  },
  {
    id: 'faux_camaieu',
    nameJa: 'フォカマイユ配色',
    category: 'nuance',
    colorCount: { min: 2, max: 3 },
    hueRule: { kind: 'diff_range', min: 0, max: 2 },
    toneRule: { kind: 'similar' },
    description: 'カマイユより少し差をつけた、似た色同士の配色。',
    impression: ['やわらかい変化', '上品', 'まとまり'],
    generationPriority: 'medium',
  },

  // ---------- harmony: 色相-トーン関係 ----------
  {
    id: 'natural_harmony',
    nameJa: 'ナチュラルハーモニー',
    category: 'harmony',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'natural_harmony' },
    toneRule: { kind: 'any' },
    description:
      '黄に近い色相を明るく、青紫に近い色相を暗くする、自然界の見え方に基づく配色。',
    impression: ['自然', '安定', '心地よい'],
    generationPriority: 'high',
  },
  {
    id: 'complex_harmony',
    nameJa: 'コンプレックスハーモニー',
    category: 'harmony',
    colorCount: { min: 2, max: 4 },
    hueRule: { kind: 'complex_harmony' },
    toneRule: { kind: 'any' },
    description: '自然のセオリーと逆の明暗関係をあえて作る、意外性のある配色。',
    impression: ['個性的', '意外性', '人工的'],
    generationPriority: 'medium',
  },

  // ---------- n_colors: 色数指定 ----------
  {
    id: 'bicolor',
    nameJa: 'ビコロール配色',
    category: 'n_colors',
    colorCount: { min: 2, max: 2 },
    hueRule: { kind: 'diff_range', min: 4, max: 12 },
    toneRule: { kind: 'contrast' },
    description: '2色の強い対比で構成する配色。',
    impression: ['明快', '対比', 'はっきり'],
    generationPriority: 'medium',
  },
  {
    id: 'tricolor',
    nameJa: 'トリコロール配色',
    category: 'n_colors',
    colorCount: { min: 3, max: 3 },
    hueRule: { kind: 'diff_range', min: 4, max: 12 },
    toneRule: { kind: 'contrast' },
    description: '3色のはっきりした対比で構成する配色(国旗のような印象)。',
    impression: ['明快', '対比', '象徴的'],
    generationPriority: 'medium',
  },

  // ---------- wheel_division: 色相環n等分 ----------
  {
    id: 'dyad',
    nameJa: 'ダイアード',
    category: 'wheel_division',
    colorCount: { min: 2, max: 2 },
    hueRule: { kind: 'equal_division', n: 2 },
    toneRule: { kind: 'any' },
    description: '色相環を2等分した正反対の2色(=補色)を使う配色。',
    impression: ['強い対比', '緊張感', '鮮やか'],
    generationPriority: 'medium',
  },
  {
    id: 'split_complementary',
    nameJa: 'スプリットコンプリメンタリー',
    category: 'wheel_division',
    colorCount: { min: 3, max: 3 },
    hueRule: { kind: 'split_complementary' },
    toneRule: { kind: 'any' },
    description: '補色の両隣を使う、対比と調和を両立した3色配色。',
    impression: ['動き', 'バランス', '対比'],
    generationPriority: 'medium',
  },
  {
    id: 'triad',
    nameJa: 'トライアド',
    category: 'wheel_division',
    colorCount: { min: 3, max: 3 },
    hueRule: { kind: 'equal_division', n: 3 },
    toneRule: { kind: 'any' },
    description: '色相環を3等分した3色を使う、安定感のある配色。',
    impression: ['活発', 'バランス', '安定'],
    generationPriority: 'high',
  },
  {
    id: 'tetrad',
    nameJa: 'テトラード',
    category: 'wheel_division',
    colorCount: { min: 4, max: 4 },
    hueRule: { kind: 'equal_division', n: 4 },
    toneRule: { kind: 'any' },
    description: '色相環を4等分した4色を使う配色。',
    impression: ['華やか', 'バランス', '多彩'],
    generationPriority: 'medium',
  },
  {
    id: 'pentad',
    nameJa: 'ペンタード',
    category: 'wheel_division',
    colorCount: { min: 5, max: 5 },
    hueRule: { kind: 'equal_division', n: 5 },
    toneRule: { kind: 'any' },
    description: '色相環を5等分した5色を使う配色。',
    impression: ['多彩', '賑やか', '装飾的'],
    generationPriority: 'low',
  },
  {
    id: 'hexad',
    nameJa: 'ヘクサード',
    category: 'wheel_division',
    colorCount: { min: 6, max: 6 },
    hueRule: { kind: 'equal_division', n: 6 },
    toneRule: { kind: 'any' },
    description: '色相環を6等分した6色を使う配色。',
    impression: ['多彩', '華やか', '賑やか'],
    generationPriority: 'low',
  },
];

export const adjustmentTechniques: AdjustmentTechnique[] = [
  {
    id: 'accent',
    nameJa: 'アクセントカラー',
    description:
      '配色全体の中で1色だけ強い対比の色を差し込み、印象を引き締める技法。',
    impression: ['引き締まる', '目を引く', 'メリハリ'],
  },
  {
    id: 'separation',
    nameJa: 'セパレーション',
    description: '隣り合う色の間に無彩色を挟むことで境界を明確にする技法。',
    impression: ['明快', '整理された', '見やすい'],
  },
  {
    id: 'gradation',
    nameJa: 'グラデーション',
    description:
      '色相・明度・彩度のいずれかを段階的に変化させて連続性を出す技法。',
    impression: ['流れ', '連続', 'リズム'],
  },
];

/**
 * 技法IDから定義を引くためのマップ。
 */
export const techniquesById: Record<string, Technique> = Object.fromEntries(
  techniques.map((t) => [t.id, t]),
);
